project_id = "flwfpjthwezlnmjutfnh"

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[auth.email]
enable_signup = true
enable_confirmations = false

[functions.send-notification]
verify_jwt = true