// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flwfpjthwezlnmjutfnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsd2ZwanRod2V6bG5tanV0Zm5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNjgyODEsImV4cCI6MjA3MDk0NDI4MX0.1L9UpeSXU5Vsw5VTTSRkBTKe6af2pAFKsTgfwRmTCas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});